site_name: PubRead

theme: mkdocs

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - mathjaxhelper.js

markdown_extensions:
    - extra
    - tables
    - fenced_code
    - footnotes

nav:
 - Home: "index.md"
 - Scripta Manent:
     - Time Series:
         - Time Series To-Read: "time_series/to_read.md"
         - Time Series Forcasting: "time_series/tsa_oct_2021.md"
     - Emergent Constraints:
         - EC To-Read: "ec/to_read.md"
         - hall2018: "ec/hall_et_al_2019.md"
         - cox2018: "ec/cox2018_meth.md"

